server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://8.130.120.83:3306/ZY_OBJ?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: Zy123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 配置Druid筛选器属性
    druid:
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 5000
        wall:
          enabled: true
          db-type: mysql
          config:
            delete-allow: false
            drop-table-allow: false
  main:
    allow-bean-definition-overriding: true

  redis:
    database: 0
    host: 8.130.120.83
    port: 6379
    timeout: 10000
    password: Zy123456
    repositories:
      enabled: false
    jedis:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 10
        min-idle: 0
  mail:
    username: 1215668319@qq.com
    host: smtp.qq.com
    port: 465
    password: pvqhcctgpswlhcbj
    sslEnable: true

mybatis-plus:
#  type-aliases-package: com.zyao.common.api.sys # 指定实体类所在包
  mapper-locations: classpath*:/mapper/**/*.xml # 用户标记或者指定mybatis对应xml的路径；
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

quartz:
  scheduler:
    instanceName: quartzScheduler
    instanceId: AUTO
  threadPool:
    class: org.quartz.simpl.SimpleThreadPool
    threadCount: 10
    threadPriority: 5
  jobStore:
    class: org.quartz.impl.jdbcjobstore.JobStoreTX
    driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
    useProperties: true
    dataSource: myDS
    tablePrefix: QRTZ_
  dataSource:
    myDS:
      driver: com.mysql.cj.jdbc.Driver
      URL: jdbc:mysql://8.130.120.83:3306/ZY_OBJ?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&serverTimezone=Asia/Shanghai&useSSL=false
      user: root
      password: Zy123456
      maxConnections: 10
  # 定时任务具体实现路径
  package:  com.zyao.job

# 租户表维护
tenant:
  enable: true
  column: tenant_id
  ignoreTables:
    - sys_user
    - sys_account
   ignoreSqls:
