server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://8.130.120.83:3306/ZY_OBJ?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: Zy123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 配置Druid筛选器属性
    druid:
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 5000
        wall:
          enabled: true
          db-type: mysql
          config:
            delete-allow: false
            drop-table-allow: false

  redis:
    database: 10
    host: 163.53.168.92
    port: 6379
    timeout: 10000
    password: Hy12345678
    repositories:
      enabled: false
    jedis:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 10
        min-idle: 0
  mail:
    username: 1215668319@qq.com
    host: smtp.qq.com
    port: 465
    password: pvqhcctgpswlhcbj
    sslEnable: true

mybatis-plus:
#  type-aliases-package: com.zyao.common.api.sys # 指定实体类所在包
  mapper-locations: classpath*:/mapper/**/*.xml # 用户标记或者指定mybatis对应xml的路径；
  configuration:
    map-underscore-to-camel-case: true

